### PR TITLE
Beta testing merge to main

### PR DESCRIPTION
**Pull request by mazfil**

### CODE REVIEW

**Comment by mazfil** [comment]
Just the one conflict for backend. 
No issues with frontend but would like a look from Alex to make sure. ty

**Comment by alexdboxall** [comment]
Conflict has been resolved, looks good to me to merge.

**Comment by Edward-Nivison** [comment]
I am all good with moving on, probably should just read over the user-testing-2.md that we made today, there are a couple issues that were discovered that we should implement.

**Comment by Edward-Nivison** [comment]
All good with it. Spoke with the team about it. Merging

**Pull request merged**
