### PR TITLE
Backend add data structures

### PR DESCRIPTION
**Pull request by alexdboxall**
Addresses issue #31.

Implements the main skeleton of the backend, and can generate random schedules, and sets up Java classes for various required components such as Courses, Rooms and Time.

After this pull request is merged, further smaller issues will be added instead of continuing work on this issue.

### CODE REVIEW

**Comment by Hexuan-Meng** [comment]
In `placeCourseRandomly(Random rng, int courseId)` in `Schedule` class, the `spacesAvailable` actually means the allocated students, we keep calling `placeLabRandomly(rng, course)` until all students of that course are allocated. 

Currently, when calculating the `count` of a `Allocation`, we are setting it to the minimum among `maxCapacity` of `Room`, `numStudents` of `Course`, and `numTutors * tutorRatio` of a `Course`. However, If the unallocated students are less than each of them, the `count` of the `Allocation` would be wrong. 

Maybe we should have a `unallocatedStudents` field in the `Course` class, and modify the method of calculating the `count` of an `Allocation` accordingly. 

Do you think calculating the `count` in the constructor of the `Allocation` is a good idea? Since currently the code calculating it spreads among `getMaximumClassSize()` in `Course` class and `placeLabRandomly(Random rng, Course course)` in `Schedule` class.

By the way, I'd also like to know is there a specific reason for setting the `count` to `0` for courses that runs across multiple 30-minute blocks?

**Comment by alexdboxall** [comment]
Those are some good points!

`spacesAvailable` refers to how many seats are available in labs, so yes it is the same thing as the number of students allocated. I can change the variable name if to make it more clear.

For your second point, it's okay for a room to have more seats than it does students - in fact it is good to overall have a few more seats allocated than there are students so that students have somewhat of a choice. `count` isn't the number of students - it's the number of seats for students. (Perhaps the commenting isn't clear enough - I'll update that).

The `count` calculation could probably be moved into the constructor of `Course`, yes.

There's no specific reason for `0` as the continuation marker for courses running across multiple blocks - we need some way of marking it though (to distinguish more easily between two back-to-back labs), and that was the easiest (laziest) way I could think of. I can change it to use a `boolean continuing;` instead if you think that's better?

**Comment by Hexuan-Meng** [comment]
Sorry for my misunderstanding of the meaning of `count`. If `count` means the number of seats for students, I think it only depends on the minimum between the `Room.maxCapacity` and `numTutors * tutorRatio` of a `Course`. The total number of enrolled students (`Course.numStudents`) does not matter.

Forget about me saying to calculate the `count` in the constructor of `Allocation`, since we don't know the room when creating an allocation. Sorry for any confusion caused.

For the continuation marker, I think using `boolean continuing;` is clearer, but both ways are fine for now.

I'm still quite confused about the naming of `spacesAvailable`, maybe changing to another name is better from my perspective.

**Comment by Edward-Nivison** [comment]
I have had a read through the code on a general level, I understand it somewhat and from my experience (which is quite little in genetic algorithms) is that it looks like it is doing what it should be doing. I see that there is quite a few conditions that we have talked over still to go and I am happy to help out with that (after watching some videos on how the algorithm works in general so I can understand thoroughly how the reward system works, so I can think of how to write out the logic). I am available to work on this the following week. so I will assign myself some correlating issues.

**Comment by alexdboxall** [comment]
@Hexuan-Meng Yes, you're right - it doesn't depend on `Course.numStudents` - I'll push a change that removes that. I'll also change `spacesAvailable` and add the `boolean continuing` instead of using a count of 0.

@Edward-Nivison Sounds good.

**Comment by alexdboxall** [comment]
I'll merge this into the dev branch now so that everyone can start working on their features - if there are further improvements we want to make to the structure of the code we can modify it later via another branch and pull request.

**Pull request merged**
