### PR TITLE
Merging new Data management page into dev

### PR DESCRIPTION
**Pull request by mazfil**

### CODE REVIEW

**Comment by mazfil** [comment]
Updated the references which was causing an error when merged into dev branch.
Lgtm for now.

@Edward-Nivison can you take a look and merge if happy, ty.

**Comment by Edward-Nivison** [comment]
It looks good. Just confirming your intentions. It is merging from 56-implement-data-management-page into dev. But your pull request title is that is going to main. Let me know which is the mistake and I am all good.

**Comment by mazfil** [comment]
> It looks good. Just confirming your intentions. It is merging from 56-implement-data-management-page into dev. But your pull request title is that is going to main. Let me know which is the mistake and I am all good.

fixed now, lil typo

**Comment by Edward-Nivison** [comment]
Looks good now. I will accept it.

**Comment by Edward-Nivison** [comment]
Referencing the relevant issue. #56

**Pull request merged**
